name: aloka_mobile_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.6

  scroll_date_picker: ^3.7.3
  path_provider: ^2.1.0
  modal_bottom_sheet: ^2.1.2

  flutter_slidable: ^3.1.2
  badges: ^3.1.2
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.7
  multi_select_flutter: ^4.1.3

#qr code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

#image 
  image_picker: ^1.0.4
  image_cropper: ^5.0.0

  fluttericon: ^2.0.0

#internet connection check
  internet_connection_checker: ^1.0.0+1
  flutter_phone_direct_caller: ^2.1.1
  connectivity_plus: ^5.0.1

#flutter bloc
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  simple_month_year_picker: ^1.0.5
  pdf: ^3.11.1
  printing: ^5.13.4
  file_picker: ^8.1.4
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  flutter_tts: ^4.2.0
  share_plus: ^10.1.3
  mobile_scanner: ^6.0.2
  http: ^1.2.2

#flutter error report
#  bugsnag_flutter: ^3.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/logo/
  - assets/icon/
  - assets/lottie/
  - assets/svg/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Regular.ttf
        - asset: assets\fonts\Poppins-Bold.ttf
        - asset: assets\fonts\Poppins-Italic.ttf
    - family: Oswald
      fonts:
        - asset: assets\fonts\Oswald-Bold.ttf
        - asset: assets\fonts\Oswald-Regular.ttf
        - asset: assets\fonts\Oswald-ExtraLight.ttf
        - asset: assets\fonts\Oswald-Medium.ttf

# splash screen
flutter_native_splash:
    color: "#ffffff"
    image: "assets/logo/brr.png"
    android: true
    ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/brr.png"
  min_sdk_android: 21 # android min sdk min:16, default 21