# Project Information
name: aloka_mobile_app
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev
version: 1.0.0+1 # Application version

# Flutter SDK version constraints
environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 # Date and time formatting
  cupertino_icons: ^1.0.6 # iOS style icons
  flutter_native_splash: ^2.3.6 # Splash screen setup

  # UI Components
  scroll_date_picker: ^3.7.3 # Scrollable date picker
  path_provider: ^2.1.0 # File path access
  modal_bottom_sheet: ^2.1.2 # Customizable bottom sheet

  flutter_slidable: ^3.1.2 # Swipeable list items
  badges: ^3.1.2 # Badge components
  percent_indicator: ^4.2.3 # Progress indicators
  flutter_svg: ^2.0.7 # SVG rendering
  multi_select_flutter: ^4.1.3 # Multi-select dropdown

  # QR Code Functionality
  qr_flutter: ^4.1.0 # Generate QR codes
  qr_code_scanner: ^1.0.1 # Scan QR codes

  # Image Handling
  image_picker: ^1.0.4 # Image selection
  image_cropper: ^5.0.0 # Crop images

  fluttericon: ^2.0.0 # Customizable icons

  # Internet Connection Management
  internet_connection_checker: ^1.0.0+1 # Internet connection monitoring
  connectivity_plus: ^5.0.1 # Connectivity status

  # State Management
  flutter_bloc: ^8.1.6 # Bloc pattern
  equatable: ^2.0.5 # Equality for bloc models

  # Utilities
  flutter_launcher_icons: ^0.13.1 # App launcher icon generator
  simple_month_year_picker: ^1.0.5 # Month-year picker
  pdf: ^3.11.1 # Generate PDFs
  printing: ^5.13.4 # Print functionality
  file_picker: ^8.1.4 # File selection
  permission_handler: ^11.3.1 # Permission management
  image_gallery_saver: ^2.0.3 # Save images to gallery
  flutter_tts: ^4.2.0 # Text-to-speech
  share_plus: ^10.1.3 # Sharing content
  mobile_scanner: ^6.0.2 # Barcode scanning
  http: ^1.2.2 # HTTP requests

# Uncomment to use Bugsnag for error reporting
#  bugsnag_flutter: ^3.1.1

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Linting rules
  build_runner: ^2.4.14 # Code generation
  mockito: ^5.4.5 # Mocking in tests

# Flutter Settings
flutter:
  uses-material-design: true # Material design usage

  # Asset Configuration
  assets:
    - assets/images/
    - assets/logo/
    - assets/svg/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-Medium.ttf

# Splash Screen Configuration
flutter_native_splash:
  color: "#ffffff" # Background color
  image: "assets/logo/brr.png" # Splash screen image
  android: true
  ios: true

# Launcher Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/brr.png"
  min_sdk_android: 21 # Android minimum SDK level (default 21, minimum 16)
