name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Install Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'  # Stable version

      # 3. Set up JDK for Android builds
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 5. Analyze the project source code
      - name: Analyze Code
        run: flutter analyze

      # 6. Run unit tests
      - name: Run Tests
        run: flutter test

      # 7. Build Release APK
      - name: Build Release APK
        run: flutter build apk --release

      # 8. Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
